const transaction = {
  tx: {
    acr_values: [],
    id: 'ANq9t98Vpe76JYy_UmROKhBm-NV__R7B',
    linking_id: null,
    locale: 'ja',
    login_hint: null,
    prompt: [],
    protocol: 'oidc-basic-profile',
    redirect_uri: 'https://kmtym-jwt-generator.vercel.app/',
    requested_authorization_details: null,
    requested_scopes: ['openid', 'read:current_user'],
    response_mode: 'web_message',
    response_type: ['code'],
    state: 'LjdkUnRRM3Fkc2pwS1Y0eVdhQll1d0ZLdXZKRkVub3pmOEp6anlUbDFEVg==',
    ui_locales: [],
  },
};

const event = {
  event: {
    transaction: {
      acr_values: [],
      id: 'aYpMWjrczZeeYA9llY-b2l6QJOE0WsP1',
      linking_id: null,
      locale: 'ja',
      login_hint: null,
      prompt: [],
      protocol: 'oidc-basic-profile',
      redirect_uri: 'https://kmtym-jwt-generator.vercel.app/',
      requested_authorization_details: null,
      requested_scopes: [Array],
      response_mode: 'web_message',
      response_type: [Array],
      state: 'cUtjQjJMZE84LjlrUzlJTmNXaFNXZXhhTUROUjlSRHVDa3JaZkpRR3RGSg==',
      ui_locales: [],
    },
    authentication: { methods: [Array] },
    authorization: { roles: [] },
    connection: {
      id: 'con_1fbP4HlbJjeb8RCw',
      metadata: {},
      name: 'Username-Password-Authentication',
      strategy: 'auth0',
    },
    organization: undefined,
    resource_server: {
      identifier: 'https://kmtym-jwt-generator.vercel.app/api',
    },
    tenant: { id: 'kmtym-jwt-generator' },
    secrets: {},
    configuration: {},
    client: {
      // 多分 application の client id
      client_id: 'bDNkJDZdbZ9AIUKhLLcTEMNg1Q0XkJSv',
      name: 'front',
      metadata: {},
    },
    request: {
      ip: '122.215.232.18',
      method: 'GET',
      query: [Object],
      body: {},
      geoip: [Object],
      hostname: 'kmtym-jwt-generator.jp.auth0.com',
      language: undefined,
      user_agent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36',
    },
    stats: { logins_count: 42 },
    user: {
      app_metadata: [Object],
      created_at: '2022-10-26T16:22:55.145Z',
      email_verified: false,
      email: 'r.komatsuyama@buysell-technologies.com',
      family_name: undefined,
      given_name: undefined,
      identities: [Array],
      last_password_reset: undefined,
      name: 'r.komatsuyama@buysell-technologies.com',
      nickname: 'r.komatsuyama',
      phone_number: undefined,
      phone_verified: undefined,
      picture:
        'https://s.gravatar.com/avatar/5a12516bad9cc202a68fe573f6bb694f?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fr.png',
      updated_at: '2023-04-21T03:42:45.236Z',
      user_id: 'auth0|63595edf479bcdf17f99194d',
      user_metadata: [Object],
      username: undefined,
      multifactor: [],
    },
  },
};
