// user, context, callback の中身
const obj = {
  user: {
    _id: '1d4bba4aa2a1f8f1829d3994c7f65dfc',
    clientID: 'bDNkJDZdbZ9AIUKhLLcTEMNg1Q0XkJSv',
    created_at: '2022-10-26T16:22:55.145Z',
    email: 'r.komatsuyama@buysell-technologies.com',
    email_verified: false,
    identities: [[Object]],
    name: 'r.komatsuyama@buysell-technologies.com',
    nickname: 'r.komatsuyama',
    picture:
      'https://s.gravatar.com/avatar/5a12516bad9cc202a68fe573f6bb694f?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fr.png',
    updated_at: '2023-04-20T13:51:47.946Z',
    user_id: 'auth0|63595edf479bcdf17f99194d',
    user_metadata: {},
    global_client_id: 'oYXGBipvr8xGfRxZ1any1WrKiN63iIOU',
    app_metadata: {
      family_name_kana: 'こまつやま',
      given_name_kana: 'りょうへい (バイセル)',
      service_ids: [Array],
      'x-hasura-store-id': '271e5f06-1f4d-48b6-b631-e6fe6ce5a3a0',
      'x-hasura-tenant-id': '9b9e2ae4-d53b-49b5-b6ae-2417060227e3',
      'x-hasura-user-id': '87b7f6bc-55da-4705-812b-b84dcca4b6b5',
      'x-hasura-allowed-roles': [Array],
      'x-hasura-default-role': 'crew',
      'x-hasura-tenant-group-id': 'ce0488c5-249d-4e3a-aed5-ee4faf7b2bf1',
    },
    family_name_kana: 'こまつやま',
    given_name_kana: 'りょうへい (バイセル)',
    service_ids: [
      'account',
      'promas',
      'exs',
      'appraisal',
      'deal',
      'portal',
      'approval',
      'core',
      'store',
    ],
    'x-hasura-store-id': '271e5f06-1f4d-48b6-b631-e6fe6ce5a3a0',
    'x-hasura-tenant-id': '9b9e2ae4-d53b-49b5-b6ae-2417060227e3',
    'x-hasura-user-id': '87b7f6bc-55da-4705-812b-b84dcca4b6b5',
    'x-hasura-allowed-roles': [
      'deal_appraisal_user',
      'manager',
      'crew',
      'promas_appraisal_user',
      'deal_appraisal_leader',
      'deal_appraisal_manager',
      'deal_store_user',
      'deal_store_manager',
      'deal_approval_user',
    ],
    'x-hasura-default-role': 'crew',
    'x-hasura-tenant-group-id': 'ce0488c5-249d-4e3a-aed5-ee4faf7b2bf1',
    persistent: {},
  },
  context: {
    tenant: 'kmtym-jwt-generator',
    clientID: 'bDNkJDZdbZ9AIUKhLLcTEMNg1Q0XkJSv',
    clientName: 'front',
    clientMetadata: {},
    connection: 'Username-Password-Authentication',
    connectionStrategy: 'auth0',
    connectionID: 'con_1fbP4HlbJjeb8RCw',
    connectionOptions: {},
    connectionMetadata: {},
    samlConfiguration: {},
    jwtConfiguration: {},
    protocol: 'oidc-basic-profile',
    stats: { loginsCount: 22 },
    sso: { with_auth0: false, with_dbconn: false },
    accessToken: { 'https://kmtym-jwt-generator.vercel.app': [Object] },
    idToken: { 'https://kmtym-jwt-generator.vercel.app': [Object] },
    authentication: { methods: [Array] },
    locale: 'ja',
    sessionID: 'LNnS0yRtnt7BLAiWd4p-dNoYnDj9-4xk',
    request: {
      userAgent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36',
      ip: '126.227.214.95',
      hostname: 'kmtym-jwt-generator.jp.auth0.com',
      method: 'GET',
      query: [Object],
      body: {},
      geoip: [Object],
    },
    authorization: { roles: [] },
  },
  callback: [Function],
};
